// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaboyuyvpkracvtwngcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhYm95dXl2cGtyYWN2dHduZ2NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTg4NDUsImV4cCI6MjA2NTUzNDg0NX0.PcnfZR3rMzSNZhCLvCS0PeRiqpPpemZtvfQAi3bcImY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);